CREATE TABLE IF NOT EXISTS MOVIE_INFO (
    ID           INT auto_increment,
    MOVIE_NAME   VARCHAR  DEFAULT ''    NOT NULL,
    LOCAL_PATH   VARCHAR  DEFAULT ''    NOT NULL,
    RELEASE_TIME VARCHAR  DEFAULT ''    NOT NULL,
    CRAETE_TIME  DATETIME DEFAULT NOW() NOT NULL,
    MODIFY_TIME  DATETIME DEFAULT NOW() NOT NULL,
    CONSTRAINT MOVIE_INFO_PK PRIMARY KEY (ID)
);